services:
  postgres:
    image: postgres
    container_name: ms-email
    restart: always
    environment:
      POSTGRES_DB: ms-email
      POSTGRES_USER: root
      POSTGRES_PASSWORD: senha-postgres
    ports:
      - "5432:5432"